// This file is auto-generated by setup-build.js
// Do not edit directly

const config = require('./next.config.mjs');

// Extract the actual configuration object
const nextConfig = config.default || config;

module.exports = nextConfig; 